package com.example.movie_catalog.entity.plug

import com.example.movie_catalog.data.api.film_info.FilmInfoDTO
import com.example.movie_catalog.data.room.tables.CollectionDB
import com.example.movie_catalog.entity.Collection
import com.example.movie_catalog.entity.Linker
import com.example.movie_catalog.entity.Film
import com.example.movie_catalog.entity.filminfo.InfoFilmSeasons
import com.example.movie_catalog.entity.enumApp.Kit
import com.example.movie_catalog.entity.Country
import com.example.movie_catalog.entity.Genre

object Plug {

    val plugLinkers = listOf(Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),
        Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),
        Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker(),Linker())

    val filmPlug = listOf(
        Film( filmId =  1115454,
            nameRu= "Портрет незнакомца",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1115454.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("мелодрама")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4661024,
            nameRu= "Золушка",
            nameEn= "Cinderella",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4661024.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("музыка")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4765774,
            nameRu= "Щенячий патруль: Миссия «Рождество»",
            nameEn= "Paw Patrol. Mission Xmas",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4765774.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("мультфильм")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  968618,
            nameRu= "Звёздный разум",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/968618.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("фантастика"), Genre("триллер")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1368311,
            nameRu= "Черный ящик",
            nameEn= "Boîte noire",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1368311.jpg",
            countries = listOf(Country("Франция")),
            genres = listOf(Genre("детектив"), Genre("триллер")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4449009,
            nameRu= "Свингеры",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4449009.jpg",
            countries = listOf(Country("Россия"), Country("Латвия")),
            genres = listOf(Genre("комедия"), Genre("мелодрама")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1304236,
            nameRu= "Мой волк",
            nameEn= "Mystère",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1304236.jpg",
            countries = listOf(Country("Франция")),
            genres = listOf(Genre("семейный"), Genre("приключения")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1354084,
            nameRu= "Джигалоу",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1354084.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1411096,
            nameRu= "Самый лучший босс",
            nameEn= "El buen patrón",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1411096.jpg",
            countries = listOf(Country("Испания")),
            genres = listOf(Genre("драма"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1332599,
            nameRu= "Проклятие монахинь",
            nameEn= "Agnes",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1332599.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("ужасы"), Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1404110,
            nameRu= "(Не)идеальные парочки",
            nameEn= "Per tutta la vita",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1404110.jpg",
            countries = listOf(Country("Италия")),
            genres = listOf(Genre("комедия"), Genre("мелодрама")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1327545,
            nameRu= "Однажды в кино",
            nameEn= "Chhello Show",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1327545.jpg",
            countries = listOf(Country("Индия"), Country("Франция"), Country("США")),
            genres = listOf(Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1336599,
            nameRu= "Звериные бои",
            nameEn= "Daisy Quokka: World's Scariest Animal",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1336599.jpg",
            countries = listOf(Country("Австралия"), Country("США")),
            genres = listOf(Genre("мультфильм"), Genre("семейный")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4716610,
            nameRu= "Наш двор. 25 лет спустя",
            nameEn= "Mer Bake 4",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4716610.jpg",
            countries = listOf(Country("Армения")),
            genres = listOf(Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1320005,
            nameRu= "Лекарство для Веры",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1320005.jpg",
            countries = listOf(Country("Беларусь")),
            genres = listOf(Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  979148,
            nameRu= "Назови меня своим именем",
            nameEn= "Call Me by Your Name",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/979148.jpg",
            countries = listOf(Country("Италия"), Country("Франция"), Country("США")),
            genres = listOf(Genre("драма"), Genre("мелодрама")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1045056,
            nameRu= "King’s Man: Начало",
            nameEn= "The King's Man",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1045056.jpg",
            countries = listOf(Country("Великобритания"), Country("США")),
            genres = listOf(Genre("боевик"), Genre("триллер"), Genre("приключения")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1328422,
            nameRu= "Крик",
            nameEn= "Scream",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1328422.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("ужасы"), Genre("детектив")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1320623,
            nameRu= "Лакричная пицца",
            nameEn= "Licorice Pizza",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1320623.jpg",
            countries = listOf(Country("США"), Country("Канада")),
            genres = listOf(Genre("драма"), Genre("мелодрама"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1033686,
            nameRu= "Одни дома",
            nameEn= "Pups Alone",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1033686.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("комедия"), Genre("семейный")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  673726,
            nameRu= "Фальшивомонетчик",
            nameEn= "Flag Day",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/673726.jpg",
            countries = listOf(Country("США"), Country("Великобритания"), Country("Канада")),
            genres = listOf(Genre("драма"), Genre("криминал")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1256427,
            nameRu= "Робот Ари",
            nameEn= "The Adventure of A.R.I.: My Robot Friend",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1256427.jpg",
            countries = listOf(Country("Франция")),
            genres = listOf(Genre("семейный"), Genre("фантастика"), Genre("приключения")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1183602,
            nameRu= "Убить босса",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1183602.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  993076,
            nameRu= "Даже мыши попадают в рай",
            nameEn= "I mysi patrí do nebe",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/993076.jpg",
            countries = listOf(Country("Чехия"), Country("Франция"), Country("Словакия")),
            genres = listOf(Genre("мультфильм"), Genre("фэнтези"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4819446,
            nameRu= "Тартюф, или Обманщик",
            nameEn= "Tartuffe, or The Hypocrite",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4819446.jpg",
            countries = listOf(Country("Франция")),
            genres = listOf(Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1435858,
            nameRu= "На краю",
            nameEn= "The Ledge",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1435858.jpg",
            countries = listOf(Country("Великобритания")),
            genres = listOf(Genre("триллер")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  49684,
            nameRu= "Ходячий замок",
            nameEn= "Howl no Ugoku Shiro",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/49684.jpg",
            countries = listOf(Country("Япония")),
            genres = listOf(Genre("аниме"), Genre("мультфильм"), Genre("фэнтези")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  7715,
            nameRu= "Фотоувеличение",
            nameEn= "Blow-Up",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/7715.jpg",
            countries = listOf(Country("Великобритания"), Country("Италия"), Country("США")),
            genres = listOf(Genre("триллер"), Genre("драма"), Genre("детектив")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1125892,
            nameRu= "Аллея кошмаров",
            nameEn= "Nightmare Alley",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1125892.jpg",
            countries = listOf(Country("США"), Country("Мексика"), Country("Канада")),
            genres = listOf(Genre("триллер"), Genre("драма"), Genre("криминал")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1118222,
            nameRu= "Код 355",
            nameEn= "The 355",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1118222.jpg",
            countries = listOf(Country("США"), Country("Китай")),
            genres = listOf(Genre("триллер"), Genre("боевик")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1113006,
            nameRu= "Тайна",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1113006.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("семейный"), Genre("приключения")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1345777,
            nameRu= "Тихая ночь",
            nameEn= "Silent Night",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1345777.jpg",
            countries = listOf(Country("Великобритания")),
            genres = listOf(Genre("драма"), Genre("комедия"), Genre("фантастика")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4308828,
            nameRu= "Антитела",
            nameEn= "The Survivalist",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4308828.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("фантастика"), Genre("боевик"), Genre("триллер")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1246017,
            nameRu= "Камелот: Возвращение короля",
            nameEn= "Kaamelott - Premier volet",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1246017.jpg",
            countries = listOf(Country("Франция"), Country("Бельгия")),
            genres = listOf(Genre("фэнтези"), Genre("комедия"), Genre("приключения")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4368677,
            nameRu= "Событие",
            nameEn= "L'événement",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4368677.jpg",
            countries = listOf(Country("Франция")),
            genres = listOf(Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1338595,
            nameRu= "Проклятый дом 5",
            nameEn= "Know Fear",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1338595.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("ужасы")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1403122,
            nameRu= "Всё прошло хорошо",
            nameEn= "Tout s'est bien passé",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1403122.jpg",
            countries = listOf(Country("Франция"), Country("Бельгия")),
            genres = listOf(Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1165082,
            nameRu= "Команда котиков",
            nameEn= "Seal Team",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1165082.jpg",
            countries = listOf(Country("ЮАР"), Country("США")),
            genres = listOf(Genre("мультфильм"), Genre("комедия"), Genre("семейный")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1236740,
            nameRu= "Голос любви",
            nameEn= "Aline",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1236740.jpg",
            countries = listOf(Country("Франция"), Country ("Канада"), Country("Бельгия")),
            genres = listOf(Genre("музыка"), Genre("мелодрама"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  635243,
            nameRu= "Руки прочь!",
            nameEn= "Tango Shalom",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/635243.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1041775,
            nameRu= "Она — океан",
            nameEn= "She Is the Ocean",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1041775.jpg",
            countries = listOf(Country("США"), Country("Германия"), Country("Индонезия")),
            genres = listOf(Genre("документальный")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1341041,
            nameRu= "9 причин, чтобы жить",
            nameEn= "Envole-moi",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1341041.jpg",
            countries = listOf(Country("Франция"), Country("Италия")),
            genres = listOf(Genre("драма"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1334748,
            nameRu= "Драгоценности",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1334748.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4822214,
            nameRu= "Мадам Баттерфляй",
            nameEn= "La Scala: Madama Butterfly",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4822214.jpg",
            countries = listOf(Country("Италия")),
            genres = listOf(Genre("музыка")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1236433,
            nameRu= "Вальдо",
            nameEn= "Last Looks",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1236433.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("триллер"), Genre("детектив"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1323108,
            nameRu= "Агент 117: Из Африки с любовью",
            nameEn= "OSS 117: Alerte rouge en Afrique noire",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1323108.jpg",
            countries = listOf(Country("Франция"), Country("Бельгия")),
            genres = listOf(Genre("боевик"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4517646,
            nameRu= "Мы — монстры 2",
            nameEn= "Monster Family 2",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4517646.jpg",
            countries = listOf(Country("Германия"), Country("Великобритания")),
            genres = listOf(Genre("мультфильм"), Genre("фэнтези"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1328678,
            nameRu= "Чемпион из Освенцима",
            nameEn= "Mistrz",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1328678.jpg",
            countries = listOf(Country("Польша")),
            genres = listOf(Genre("биография"), Genre("военный"), Genre("спорт")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1436035,
            nameRu= "Я — Златан",
            nameEn= "Jag är Zlatan",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1436035.jpg",
            countries = listOf(Country("Швеция"), Country("Дания"), Country("Нидерланды")),
            genres = listOf(Genre("драма"), Genre("биография"), Genre("спорт")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1325039,
            nameRu= "Один на один",
            nameEn= "Nowhere Special",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1325039.jpg",
            countries = listOf(Country("Великобритания"), Country("Италия"), Country("Румыния")),
            genres = listOf(Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4491071,
            nameRu= "Мария. Спасти Москву",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4491071.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("драма"), Genre("военный"), Genre("история")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1222038,
            nameRu= "Мой легионер",
            nameEn= "Mon légionnaire",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1222038.jpg",
            countries = listOf(Country("Бельгия"), Country("Франция")),
            genres = listOf(Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4421230,
            nameRu= "Любовь как бестселлер",
            nameEn= "Book of Love",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4421230.jpg",
            countries = listOf(Country("Великобритания"), Country("США"), Country("Мексика")),
            genres = listOf(Genre("мелодрама"), Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1311545,
            nameRu= "Сдохнуть нужно, чтоб вы приехали",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1311545.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("комедия"), Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4552644,
            nameRu= "Обходные пути",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4552644.jpg",
            countries = listOf(Country("Россия"), Country("Нидерланды")),
            genres = listOf(Genre("документальный"), Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1411901,
            nameRu= "Спасти планету",
            nameEn= "Escape from Extinction",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1411901.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("документальный")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  1146119,
            nameRu= "Исправь меня, если сможешь",
            nameEn= "Abbi Fede",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1146119.jpg",
            countries = listOf(Country("Италия"), Country("Австрия")),
            genres = listOf(Genre("комедия")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4742508,
            nameRu= "Леопольдштадт",
            nameEn= "Leopoldstadt",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4742508.jpg",
            countries = listOf(Country("Великобритания")),
            genres = listOf(Genre("драма")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4833814,
            nameRu= "МУЛЬТ в кино 135. Улыбка до ушей",
            nameEn= "",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4833814.jpg",
            countries = listOf(Country("Россия")),
            genres = listOf(Genre("мультфильм"), Genre("детский")),
            // kit = Kit.PREMIERES
        ),
        Film( filmId =  4661022,
            nameRu= "Риголетто",
            nameEn= "Rigoletto",
            posterUrlPreview= "https://kinopoiskapiunofficial.tech/images/posters/kp_small/4661022.jpg",
            countries = listOf(Country("США")),
            genres = listOf(Genre("музыка")),
            // kit = Kit.PREMIERES
        )
    )
//    val listCollection = listOf(
//        CollectionDB(Collection( name = "Хочу посмотреть", count = 2)),
//        CollectionDB(Collection( name = "Любимые",  count = 3)),
//        CollectionDB(Collection( name = "Другие",  count = 4)),
//        CollectionDB(Collection( name = "Не хочу посмотреть", count = 5))
//    )

    val listLinkers = listOf(
        Linker(film = filmPlug[0], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[1], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[2], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[3], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[4], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[5], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[6], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[7], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[8], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[9], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[10], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[11], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[12], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[13], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[14], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[15], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[16], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[17], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[18], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[19], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[20], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[21], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),
        Linker(film = filmPlug[22], similarFilm = null, person = null, profKey = null, kit = Kit.PREMIERES),

        )
    val infoFilmSeasonPlug = InfoFilmSeasons(
        infoFilm = FilmInfoDTO(
            kinopoiskId = 1115454,
            imdbId = "tt8350400",
            nameRu = "Портрет незнакомца",
            nameEn = null,
            nameOriginal = null,
            posterUrl = "https://kinopoiskapiunofficial.tech/images/posters/kp/1115454.jpg",
            posterUrlPreview = "https://kinopoiskapiunofficial.tech/images/posters/kp_small/1115454.jpg",
            coverUrl = "https://avatars.mds.yandex.net/get-ott/223007/2a0000017e43e962be8528002243e04aaa55/orig",
            logoUrl = "https://avatars.mds.yandex.net/get-ott/1652588/2a0000017e15b549e9d2b3f219ee1d1d997c/orig",
            reviewsCount = 1,
            ratingGoodReview = null,
            ratingGoodReviewVoteCount = 0,
            ratingKinopoisk = 6.0,
            ratingKinopoiskVoteCount = "1214",
            ratingImdb = 5.6,
            ratingImdbVoteCount = 31,
            ratingFilmCritics = null,
            ratingFilmCriticsVoteCount = 0,
            ratingAwait = 96.2,
            ratingAwaitCount = 848,
            ratingRfCritics = null,
            ratingRfCriticsVoteCount = 0,
            webUrl = "https://www.kinopoisk.ru/film/1115454/",
            year = 2021,
            filmLength = 107,
            slogan = null,
            description = "Москва. 1974 год. Актёру Олегу под сорок, у него усталый взгляд, обаятельная улыбка и глубокий бархатный голос. Он работает на радио. Артистическая судьба его не сложилась: из театра ушел, в кино ролей нет. На радио он играет в бесконечной постановке про советского шпиона, который под видом успешного бизнесмена — мистера Брауна — живет в Америке; и это его единственный заработок. \n\nОднажды радиопьесу закрывают, а жена выставляет Олега из дома. Эти довольно заурядные обстоятельства приводят к совершенно неожиданному развитию событий как в жизни героя, так и в жизни окружающих его людей — артистов радио, поэтов и писателей, официантов и проводниц поездов дальнего следования, дам полусвета и ответственных партийных работников, милиционеров, кинорежиссеров, священников, советских разведчиков и американских шпионов.",
            shortDescription = "Артист-неудачник попадает в шпионский скандал. Фееричная ретродрамеди с труппой «Мастерской Петра Фоменко»",
            editorAnnotation = null,
            isTicketsAvailable = false,
            productionStatus = null,
            type = "FILM",
            ratingMpaa = null,
            ratingAgeLimits = "age16",
            countries = listOf(Country( "Россия")),
            genres = listOf(Genre("мелодрама")),
            startYear = null,
            endYear = null,
            serial = false,
            shortFilm = false,
            completed = false,
            hasImax = false,
            has3D = false,
            lastSync = "2022-11-07T02:41:44.172668"
        )
    )
}